name: Analyse Quotidienne Football

on:
  schedule:
    - cron: '0 9 * * *'  # 9h UTC = 11h Belgique (hiver), 10h (été)
  workflow_dispatch:  # Permet déclenchement manuel

permissions:
  contents: write  # Nécessaire pour git push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run analysis
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/main.py
      
      - name: Commit predictions
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Créer le dossier data s'il n'existe pas
          mkdir -p data

          # Ajouter les changements s'il y en a (prédictions + performance_history)
          git add data/predictions/ data/performance_history.json || true

          # Commit seulement s'il y a des changements
          if git diff --staged --quiet; then
            echo "Aucun changement à commit"
          else
            git commit -m "📊 Prédictions $(date +'%Y-%m-%d')"
            git push
          fi