name: Rapport Hebdomadaire

on:
  schedule:
    # Tous les lundis à 9h00 UTC (10h Belgique hiver, 11h été)
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Permet déclenchement manuel

permissions:
  contents: read

jobs:
  weekly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate and send weekly report
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/weekly_report.py
